### ISSUE TITLE
Enable issues to be raised to Kong kafka fork

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/lua-resty-kafka#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1

### Current Behavior

Per:
https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

Can you please open an issues section for:
https://github.com/Kong/lua-resty-kafka as it introduces new fields but am not seeing tests involving those new fields for formatting purposes of my own certs/keys. Would like to either see readme providing more clarification or some sample data.

Would like to raise a point on the:
client_cert
client_priv_key

Fields as reaching of the maintainers via email from the repo's readme was not effective in gaining an answer(the Kong maintainer email does not even exist any longer so guessing left the company):

![image](https://user-images.githubusercontent.com/31913027/134521595-e4e9e825-5d18-4a9f-9dca-86226eb2eae0.png)

![image](https://user-images.githubusercontent.com/31913027/134521716-a869f3e4-81fc-406a-bed7-e74ad327bcf7.png)

Or if there is a more appropriate channel or email I could direct this request to for adding issues to your forked repos let me know! I think forked repos by default should enable issues because new functionality can be added that the origin never supports.

Thx,
Jeremy

### Expected Behavior

NA

### Steps To Reproduce

```markdown
NA
```

### Anything else?

NA

**Comment by jeremyjpj0916** [comment]
Hmm after fixing the log since index is nil I see:
```
[lua] producer.lua:274: buffered messages send to kafka err: , retryable: true, topic: com_eis_dasi_ness_uhgwm110-019282_dev_core, partition_id: 1, length: 1, context: ngx.timer, client: 10.175.232.7, server: 0.0.0.0:8000
```
and
```
[lua] producer.lua:183: _send(): retry to send messages to kafka err: nil, retryable: false, topic: com_eis_dasi_ness_uhgwm110-019282_dev_core, partition_id: 1, context: ngx.timer, client: 10.204.120.7, server: 0.0.0.0:8000
```
@jschmid1  . Would Kong 2.4.1 have the necessary underlying dependencies this kong kafka logging implementation needs? 

```
/ $ kong version --vv
2021/09/27 16:18:49 [verbose] Kong: 2.4.1
2021/09/27 16:18:49 [debug] ngx_lua: 10019
2021/09/27 16:18:49 [debug] nginx: 1019003
2021/09/27 16:18:49 [debug] Lua: LuaJIT 2.1.0-beta3
2.4.1
```
I would think so since my original SSL connection implementation worked fine before trying this mtls enabled underlying lib yall wrote up in a fork.

**Comment by jschmid1** [comment]
@jeremyjpj0916 Yes, kong 2.4.x should work fine.

**Comment by jeremyjpj0916** [comment]
Thats what I was thinking. Hmm wish the lib gave better insight since a nil or blank err field isn't much help haha. No fault of Kongs since thats original source code behavior, not yalls additions.

**Comment by jschmid1** [comment]
The lib indeed isn't very precise in case of errors. We'd absolutely appreciate patches if you happen to find a good way to improve that.

**Comment by jeremyjpj0916** [comment]
For sure, will add some more debug patching logs to these files and see if we can nail down where the actual issue is.

For the record our config is like so in the higher level plugin:
```
 "config": {
    "producer_async_buffering_limits_messages_in_memory": 50000,
    "topic": "com_eis_dasi_ness_uhgwm110-019282_dev_core",
    "keepalive": 60000,
    "bootstrap_servers": [
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093",
      "server.com:9093"
    ],
    "client_cert": "-----BEGIN CERTIFICATE-----\nXXXXXXXXXXX\n-----END CERTIFICATE----",
    "client_priv_key": "-----BEGIN RSA PRIVATE KEY-----\nXXXXXXXXXXX\n-----END RSA PRIVATE KEY-----",
    "ssl": true,
    "producer_request_acks": 1,
    "producer_request_timeout": 2000,
    "producer_request_limits_messages_per_request": 200,
    "timeout": 10000,
    "producer_request_limits_bytes_per_request": 1048576,
    "producer_request_retries_max_attempts": 10,
    "producer_request_retries_backoff_timeout": 100,
    "producer_async": true,
    "ask_id": "UHGWM110-019282",
    "app_name": "StargateSharedDevCore",
    "producer_async_flush_timeout": 1000,
    "ssl_verify": false
  }
```
I would think ssl true without requiring the client to do ssl verification is fine for mtls on the client side, meaning client will still send the cert deets over the wire but not require server side verification. Makes it more 1 way TLS but thats fine I just want to auth to the topic over TLS.

And the team providing the kafka topic gives us these deets. I see it has 2 partitions but I am no Kafka expert but imagine thats irrelevant to our errors:

![image](https://user-images.githubusercontent.com/31913027/135041251-07ca33d9-af9e-461e-a718-cdb5895fb7ef.png)

**Comment by jschmid1** [comment]
lets close this for now. Feel free to re-create since the original topic is resolved
